{
 "title": "Cyrpto App",
 "time": { "from": "2024-04-01T11:14:02.474Z", "to": "2024-04-01T11:34:37.651Z" },
 "panels": [
  {
   "title": "SOLANA USDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT price, \"timestamp\" FROM soldata "
    }
   ]
  },
  {
   "title": "ETH USDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT price, \"timestamp\" FROM ethdata "
    }
   ]
  },
  {
   "title": "BTC USDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT price, \"timestamp\" FROM btcdata "
    }
   ]
  }
 ]
}