version: '3.1'

services:

  db:
    image : postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: postgres

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
